name: SU95X - Experimental
on:
  push:
    branches:
      - experimental
    paths:
      - '.github/workflows/su95x-experimental.yml'
      - 'hdw-common/**'
      - 'hdw-su95x/**'
      - 'scripts/build-su95x.js'
      - 'scripts/build-su95x.sh'
      - 'su95x-igniter.config.mjs'
      - 'package.json'
      - 'package-lock.json'
      - 'flybywire'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HDW_PRODUCTION_BUILD: 1
      STANDALONE_ZIP_NAME: headwindsim-aircraft-su100-95-dev.zip
      BUILD_DIR_NAME: experimental
      CLOUDFLARE_WORKER_PASSWORD: ${{ secrets.CLOUDFLARE_WORKER_PASSWORD }}
      CDN_BUCKET_DESTINATION: addons/su95x/experimental
      AIRCRAFT_PROJECT_PREFIX: su95x
      AIRCRAFT_VARIANT: su100-95
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo HDW_PRODUCTION_BUILD=1 >> hdw-su95x/.env
          echo CLIENT_ID=\"${{ secrets.NAVIGRAPH_CLIENT_ID }}\" >> hdw-su95x/.env
          echo CLIENT_SECRET=\"${{ secrets.NAVIGRAPH_CLIENT_SECRET }}\" >> hdw-su95x/.env
          echo SENTRY_DSN=\"${{ secrets.SENTRY_DSN }}\" >> hdw-su95x/.env
          echo AIRCRAFT_PROJECT_PREFIX=${{ env.AIRCRAFT_PROJECT_PREFIX }} >> hdw-su95x/.env
          echo AIRCRAFT_VARIANT=${{ env.AIRCRAFT_VARIANT }} >> hdw-su95x/.env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
          echo VITE_BUILD=false >> .env
      - name: Setup Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh --clean
      - name: Copy Sources
        run: |
          ./scripts/dev-env/run.sh ./scripts/copy_su95x.sh
      - name: Build SU95X Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/build_su95x.sh --no-tty -j 4
          docker system prune -af
      - name: Build Fragmenter modules
        run: |
          node ./scripts/fragment-su95x.js
          cp ./build-su95x/out/build-modules/modules.json ./build-su95x/out/headwindsim-aircraft-su100-95/install.json
          node ./scripts/install-source-su95x.js
      - name: Upload to CloudFlare CDN
        run: |
          ./scripts/cdn.sh $CDN_BUCKET_DESTINATION ./build-su95x/out/build-modules
